### ISSUE TITLE
Union types should allow "null" in any position

### ISSUE THREAD

**Issue by chupaty** [lerouxrgd/rsgen-avro#39]
Using the following schema:
```
{
    "type": "record",
    "name": "test",
    "fields": [
        {"name": "a", "type": ["long","null"] }
    ]
}
```
rsgen-avro errors with:
```
Templating error: Invalid Schema::Null not in first position on an UnionSchema variants
```
I don't see a requirement in the avro spec about this (we do have additional requirements when we have a default value, but this doesn't apply here).

**Comment by martin-g** [comment]
I think the reason for the current implementation is the following text from the [spec](https://avro.apache.org/docs/1.11.1/specification/#unions): `Thus, for unions containing “null”, the “null” is usually listed first, since the default value of such unions is typically null.`

But I agree that it could be improved to support your use case. And the spec says `usually`, not `mandatory`.

I will send a PR!

**Comment by lerouxrgd** [comment]
This crate will make the conservative approach of using "null" only in first position as otherwise things get really too complicated.

**Comment by lerouxrgd** [comment]
(Although this can be reconsidered when later, when it's supported in `apache-avro` etc)
